version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - pos_db_data:/var/lib/postgresql/data
    networks:
      - posnet

backend:
  image: ghcr.io/git-terje/hass-backend:latest
  restart: unless-stopped
  environment:
    DATABASE_URL: postgres://posuser:pospass@db:5432/posdb
  expose:
    - "8000"
  networks:
    - posnet

frontend:
  image: ghcr.io/git-terje/hass-frontend:latest
  restart: unless-stopped
  depends_on:
    - backend
  ports:
    - "8180:80"
  networks:
    - posnet

volumes:
  pos_db_data:

networks:
  posnet:
    driver: bridge
