version: "3.8"

services:
  backend:
    image: ghcr.io/git-terje/hass-backend:latest
    container_name: hass-backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/git-terje/hass-frontend:latest
    container_name: hass-frontend
    restart: always
    ports:
      - "3000:3000"

  pos_pot:
    image: ghcr.io/git-terje/pos_pot:latest
    container_name: pos-pot
    restart: always
    ports:
      - "8180:8180"
    environment:
      - DATABASE_URL=mysql+pymysql://homeassistant:deploy@core-mariadb/homeassistant  pos_db_data:

networks:
  posnet:
    driver: bridge
