version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
      POSTGRES_DB: posdb
    volumes:
      - pos_db_data:/var/lib/postgresql/data
    networks:
      - posnet

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://posuser:pospass@db:5432/posdb
    expose:
      - "8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    networks:
      - posnet

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8180:80"
    networks:
      - posnet

volumes:
  pos_db_data:

networks:
  posnet:
    driver: bridge
