get_logs:
  name: Get Logs
  description: Fetch latest system logs (HA + Supervisor, only ERROR/WARNING).
  fields:
    lines:
      description: Number of log lines to return
      example: 100
      default: 100
      required: false
      selector:
        number:
          min: 10
          max: 1000
          unit_of_measurement: lines
