name: Build & Publish HA POS Add-on

on:
  push:
    branches:
      - main
    paths:
      - 'addons/ha_pos/**'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Add-on Image
        uses: docker/build-push-action@v5
        with:
          context: ./addons/ha_pos
          file: ./addons/ha_pos/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha_pos:latest
            ghcr.io/${{ github.repository_owner }}/ha_pos:${{ github.ref_name }}
