name: Build Home Assistant Add-ons

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ha_sysinfo, pos_pot]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Home Assistant builder leser build.json automatisk
      - name: Build and push add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addons/${{ matrix.addon }}
