name: Build and Publish Add-ons

on:
  push:
    branches:
      - main
    paths:
      - "addons/**"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate addons.json dynamically
        run: |
          python3 .github/scripts/generate_addons.py

      - name: Build and push each addon
        run: |
          for addon in addons/*; do
            if [ -f "$addon/config.json" ]; then
              name=$(jq -r '.slug' $addon/config.json)
              version=$(jq -r '.version' $addon/config.json)
              echo "🔨 Building $name:$version"

              docker buildx build \
                --platform linux/amd64,linux/arm64 \
                -t ghcr.io/${{ github.repository_owner }}/$name:$version \
                -t ghcr.io/${{ github.repository_owner }}/$name:latest \
                --push $addon
            fi
          done
