name: Deploy Home Assistant Add-ons

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ha_sysinfo, pos_pot]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push add-on
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}:${{ github.ref_name }} \
            addons/${{ matrix.addon }} \
            --push

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/pos
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
