name: Deploy Home Assistant Add-ons

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [pos_pot, openthc_pos, ha_sysinfo]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push add-on
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ matrix.addon }}:latest \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ matrix.addon }}:${{ github.ref_name }} \
            addons/${{ matrix.addon }} \
            --push
